// Build-time fetch of album art covers from the iTunes Search API. Idempotent.
// Run: `npm run cover`. Output lives at src/data/album-art.ts and is imported
// by Jumap / Juward components.
//
// iTunes Search API: https://itunes.apple.com/search?term=ARTIST+TITLE&entity=song&limit=1
//   - public, no auth, no key required
//   - artworkUrl100 → hot-linkable Apple CDN URL; `100x100` is swapped for
//     `600x600` here for clarity.

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { artists } from '../src/data/jumap.ts'
import {
  otherRanking,
  jpopRanking,
  otherNominees,
  jpopNominees,
} from '../src/data/juward.ts'

const here = path.dirname(fileURLToPath(import.meta.url))
const outPath = path.join(here, '..', 'src', 'data', 'album-art.ts')

const SEP = '|||'
const pairs = new Set<string>()
function add(artist: string, title: string) {
  if (!title) return
  if (title.startsWith('—') || title.startsWith('?')) return
  if (artist.startsWith('—')) return
  pairs.add(`${artist}${SEP}${title}`)
}

// Songs from the Jumap roster
for (const a of artists) for (const s of a.songs) add(a.name, s.title)

// Songs in the cumulative rankings
for (const r of otherRanking) for (const p of r.picks) add(p.artist, p.title)
for (const r of jpopRanking)  for (const p of r.picks) add(p.artist, p.title)

// Songs in the nominee lists
for (const y of Object.keys(otherNominees).map(Number)) {
  for (const n of otherNominees[y]) for (const song of n.songs) add(n.artist, song)
}
for (const y of Object.keys(jpopNominees).map(Number)) {
  for (const n of jpopNominees[y]) for (const song of n.songs) add(n.artist, song)
}

console.log(`Fetching ${pairs.size} unique (artist, title) pairs...`)

interface ItunesHit {
  artworkUrl100?: string
  collectionName?: string
  trackName?: string
  artistName?: string
}
interface ItunesResp {
  resultCount: number
  results: ItunesHit[]
}

async function fetchJson(url: string, attempt = 0): Promise<ItunesResp | null> {
  try {
    const r = await fetch(url)
    const text = await r.text()
    if (text.startsWith('Rate limit')) {
      if (attempt < 3) {
        const wait = 1500 * (attempt + 1)
        console.log(`    rate limited, waiting ${wait}ms (attempt ${attempt + 1})`)
        await new Promise((r) => setTimeout(r, wait))
        return fetchJson(url, attempt + 1)
      }
      return null
    }
    return JSON.parse(text) as ItunesResp
  } catch (e) {
    console.error(`  ! fetch failed: ${e}`)
    return null
  }
}

async function lookup(artist: string, title: string): Promise<string | null> {
  const queries = [
    `${artist} ${title}`,
    `${artist}`,
    `${title}`,
  ]
  for (const q of queries) {
    const url = `https://itunes.apple.com/search?term=${encodeURIComponent(q)}&entity=song&limit=5`
    const data = await fetchJson(url)
    if (data && data.resultCount > 0) {
      const al = artist.toLowerCase()
      const tl = title.toLowerCase()
      const pick = data.results.find((h) =>
        (h.artistName?.toLowerCase().includes(al) || al.includes(h.artistName?.toLowerCase() ?? '')) &&
        (h.trackName?.toLowerCase().includes(tl) || tl.includes(h.trackName?.toLowerCase() ?? '')),
      ) ?? data.results[0]
      if (pick.artworkUrl100) {
        return pick.artworkUrl100.replace('100x100', '600x600')
      }
    }
    await new Promise((r) => setTimeout(r, 250))
  }
  return null
}

const out: Record<string, string> = {}
let ok = 0, miss = 0
for (const key of pairs) {
  const [artist, title] = key.split(SEP)
  const art = await lookup(artist, title)
  if (art) {
    out[`${artist}|${title}`] = art
    ok++
    console.log(`  ✓ ${artist} — ${title}`)
  } else {
    miss++
    console.log(`  · ${artist} — ${title}`)
  }
  await new Promise((r) => setTimeout(r, 350))  // polite to Apple
}

const ts = `// AUTO-GENERATED by scripts/fetch-album-art.ts — do not edit by hand.
// Run \`npm run cover\` to refresh after adding songs.
// Keys are \`<artist>|<title>\`.

export const ALBUM_ART: Record<string, string> = ${JSON.stringify(out, null, 2)}

export function albumArtFor(artist: string, title: string): string | undefined {
  return ALBUM_ART[\`\${artist}|\${title}\`]
}
`
fs.writeFileSync(outPath, ts, 'utf8')
console.log(`\nWrote ${ok} entries to ${outPath} (${miss} not found)`)
