// Build-time fetch of artist portraits from the Wikipedia REST API.
// Output: src/data/artist-photos.ts, keyed by artist name.
//
// Wikipedia REST: https://en.wikipedia.org/api/rest_v1/page/summary/{slug}
//   - public, no auth
//   - returns a `thumbnail.source` URL when one exists
//   - we try a handful of slug variations because spaces, & and !
//     parts of band names sometimes need different encoding.

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { artists } from '../src/data/jumap.ts'
import {
  otherRanking,
  jpopRanking,
  otherNominees,
  jpopNominees,
} from '../src/data/juward.ts'

const here = path.dirname(fileURLToPath(import.meta.url))
const outPath = path.join(here, '..', 'src', 'data', 'artist-photos.ts')

const names = new Set<string>()
for (const a of artists) names.add(a.name)
for (const r of otherRanking) for (const p of r.picks) names.add(p.artist)
for (const r of jpopRanking)  for (const p of r.picks) names.add(p.artist)
for (const y of Object.values(otherNominees)) for (const n of y) names.add(n.artist)
for (const y of Object.values(jpopNominees))  for (const n of y) names.add(n.artist)

// Drop placeholder rows like "— (TBD)" and similar.
for (const n of [...names]) {
  if (n.startsWith('—') || n.startsWith('?')) names.delete(n)
}

console.log(`Fetching portraits for ${names.size} artists...`)

const UA = 'JunBio/1.0 (https://junst.github.io contact: arsol970812@gmail.com)'

async function fetchJson(url: string): Promise<{ thumbnail?: { source: string } } | null> {
  try {
    const r = await fetch(url, { headers: { 'User-Agent': UA } })
    if (!r.ok) return null
    return (await r.json()) as { thumbnail?: { source: string } }
  } catch {
    return null
  }
}

function slugVariations(name: string): string[] {
  const base = name.replace(/ /g, '_')
  const vs = new Set<string>([
    base,
    name.replace(/\s+/g, '_').replace(/&/g, 'and'),
    name.replace(/\s+/g, '_').replace(/!/g, ''),
  ])
  // A handful of curated overrides where the obvious slug is wrong
  const overrides: Record<string, string[]> = {
    'ARASHI':              ['Arashi_(band)'],
    'ReoNa':               ['ReoNa', 'ReoNa_(singer)'],
    'King & Prince':       ['King_%26_Prince_(band)', 'King_and_Prince_(band)'],
    'Drake':               ['Drake_(musician)'],
    'Buono!':              ['Buono!', 'Buono!_(band)'],
    'Snow Man':            ['Snow_Man_(Japanese_band)', 'Snow_Man_(group)'],
    'BIGBANG':             ['BigBang_(South_Korean_band)', 'BIGBANG_(South_Korean_band)'],
    'Girls’ Generation':   ['Girls%27_Generation'],
    'TWICE':               ['Twice_(group)'],
    'Red Velvet':          ['Red_Velvet_(group)'],
    'BTS':                 ['BTS'],
    'Hoshino Gen':         ['Gen_Hoshino'],
    'Beenzino':            ['Beenzino'],
    'Hey! Say! JUMP':      ['Hey!_Say!_JUMP'],
    'aespa':               ['Aespa'],
    'ILLIT':               ['Illit'],
    'TVXQ':                ['TVXQ'],
    'LE SSERAFIM':         ['Le_Sserafim'],
    'RADWIMPS':            ['Radwimps'],
    'SEKAI NO OWARI':      ['Sekai_no_Owari'],
    'Number_i':            ['Number_i'],
    'Naniwa Danshi':       ['Naniwa_Danshi'],
    'Ikimonogakari':       ['Ikimonogakari'],
    'Official髭男dism':     ['Official_Hige_Dandism'],
    'Zico & Lilas':        ['Zico_(rapper)', 'Lilas_Ikuta'],
    'Travis Scott':        ['Travis_Scott'],
    'Playboi Carti':       ['Playboi_Carti'],
    'Post Malone':         ['Post_Malone'],
    'NewJeans':            ['NewJeans'],
    'BOYNEXTDOOR':         ['Boynextdoor'],
    'Hearts2Hearts':       ['Hearts2Hearts'],
    'Sik-K & Lil Moshpit': ['Sik-K'],
    'Billie Eilish':       ['Billie_Eilish'],
    'Perfume':             ['Perfume_(Japanese_band)'],
    'SMAP':                ['SMAP'],
  }
  if (overrides[name]) for (const o of overrides[name]) vs.add(o)
  return [...vs]
}

const out: Record<string, string> = {}
let ok = 0, miss = 0
for (const name of names) {
  let found: string | null = null
  for (const slug of slugVariations(name)) {
    const url = `https://en.wikipedia.org/api/rest_v1/page/summary/${slug}`
    const data = await fetchJson(url)
    const src = data?.thumbnail?.source
    if (src) { found = src; break }
    await new Promise((r) => setTimeout(r, 200))
  }
  if (found) { out[name] = found; ok++; console.log(`  ✓ ${name}`) }
  else        { miss++; console.log(`  · ${name}`) }
  await new Promise((r) => setTimeout(r, 700))
}

const ts = `// AUTO-GENERATED by scripts/fetch-artist-photos.ts.
// Wikipedia thumbnail URLs keyed by artist name (exact match against the
// strings used in jumap.ts / juward.ts).

export const ARTIST_PHOTOS: Record<string, string> = ${JSON.stringify(out, null, 2)}

export function artistPhotoFor(name: string): string | undefined {
  return ARTIST_PHOTOS[name]
}
`
fs.writeFileSync(outPath, ts, 'utf8')
console.log(`\nWrote ${ok} entries (${miss} missing).`)
