// AUTO-GENERATED by scripts/fetch-artist-photos.ts.
// Wikipedia thumbnail URLs keyed by artist name (exact match against the
// strings used in jumap.ts / juward.ts).

export const ARTIST_PHOTOS: Record<string, string> = {
  "ARASHI": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/ARASHI_mengguncang_Jakarta%21_1m_5s.jpg/330px-ARASHI_mengguncang_Jakarta%21_1m_5s.jpg",
  "Drake": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Drake_at_The_Carter_Effect_2017_%2836818935200%29_%28cropped%29.jpg/330px-Drake_at_The_Carter_Effect_2017_%2836818935200%29_%28cropped%29.jpg",
  "Travis Scott": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/2025-0120_Cole_Gahagan_Michael_Rubin_Travis_Scott_%28cropped%29.jpg/330px-2025-0120_Cole_Gahagan_Michael_Rubin_Travis_Scott_%28cropped%29.jpg",
  "Post Malone": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Post_Malone_July_2021_%28cropped%29.jpg/330px-Post_Malone_July_2021_%28cropped%29.jpg",
  "BIGBANG": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/BIGBANG_2011_%28current_members_since_2023%29.jpg/330px-BIGBANG_2011_%28current_members_since_2023%29.jpg",
  "Girls’ Generation": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/220728_GG_poleposition_266_%2853595169645%29.jpg/330px-220728_GG_poleposition_266_%2853595169645%29.jpg",
  "Beenzino": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/190521_%EB%B9%88%EC%A7%80%EB%85%B8X%ED%99%8D%EC%A2%85%ED%98%84%2C_%EA%B0%90%ED%83%84%EB%82%98%EC%98%A4%EB%8A%94_%EB%A9%8B%EC%A7%90_%27%EB%B0%94%EC%9D%B4%EB%A0%88%EB%8F%84%28BYREDO%29%27_%ED%94%8C%EB%9E%98%EA%B7%B8%EC%8B%AD_%EC%8A%A4%ED%86%A0%EC%96%B4_%EC%98%A4%ED%94%88_%EA%B8%B0%EB%85%90%ED%96%89%EC%82%AC_36s.jpg/330px-190521_%EB%B9%88%EC%A7%80%EB%85%B8X%ED%99%8D%EC%A2%85%ED%98%84%2C_%EA%B0%90%ED%83%84%EB%82%98%EC%98%A4%EB%8A%94_%EB%A9%8B%EC%A7%90_%27%EB%B0%94%EC%9D%B4%EB%A0%88%EB%8F%84%28BYREDO%29%27_%ED%94%8C%EB%9E%98%EA%B7%B8%EC%8B%AD_%EC%8A%A4%ED%86%A0%EC%96%B4_%EC%98%A4%ED%94%88_%EA%B8%B0%EB%85%90%ED%96%89%EC%82%AC_36s.jpg",
  "BTS": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/BTS_during_a_White_House_press_conference_May_31%2C_2022_%28cropped%29.jpg/330px-BTS_during_a_White_House_press_conference_May_31%2C_2022_%28cropped%29.jpg",
  "TWICE": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Twice_-_Dickies_Arena%2C_2022_%28cropped%29.jpg/330px-Twice_-_Dickies_Arena%2C_2022_%28cropped%29.jpg",
  "Billie Eilish": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/BillieEilishO2140725-39_-_54665577407_%28cropped%29.jpg/330px-BillieEilishO2140725-39_-_54665577407_%28cropped%29.jpg",
  "Red Velvet": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/%EB%A0%88%EB%93%9C%EB%B2%A8%EB%B2%B3%28Red_Velvet%29_%EC%BC%80%EC%9D%B4%EC%BD%98_%EC%9E%AC%ED%8C%AC_2024_%EB%A0%88%EB%93%9C%EC%B9%B4%ED%8E%AB_KCON_JAPAN_2024_%281%29.jpg/330px-%EB%A0%88%EB%93%9C%EB%B2%A8%EB%B2%B3%28Red_Velvet%29_%EC%BC%80%EC%9D%B4%EC%BD%98_%EC%9E%AC%ED%8C%AC_2024_%EB%A0%88%EB%93%9C%EC%B9%B4%ED%8E%AB_KCON_JAPAN_2024_%281%29.jpg",
  "NewJeans": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/NewJeans_2023_MelonMusicAwards_composite.jpg/330px-NewJeans_2023_MelonMusicAwards_composite.jpg",
  "ILLIT": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Illit_in_January_2026.png/330px-Illit_in_January_2026.png",
  "Buono!": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Buono%21_performing_at_Japan_Expo_2014.jpg/330px-Buono%21_performing_at_Japan_Expo_2014.jpg",
  "TVXQ": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/TVXQ_December_2023.jpg/330px-TVXQ_December_2023.jpg",
  "Perfume": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/A-chan%2C_Nocchi_%26_Kashiyuka_%28Perfume%29_%22We_Are_Perfume%22_at_Opening_Ceremony_of_the_28th_Tokyo_International_Film_Festival_%2822415969052%29.jpg/330px-A-chan%2C_Nocchi_%26_Kashiyuka_%28Perfume%29_%22We_Are_Perfume%22_at_Opening_Ceremony_of_the_28th_Tokyo_International_Film_Festival_%2822415969052%29.jpg",
  "SMAP": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/SMAP_2008_Super_Modern_Artistic_Performance_Tour.jpg/330px-SMAP_2008_Super_Modern_Artistic_Performance_Tour.jpg",
  "SEKAI NO OWARI": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/SEKAINOOWARISpaceShowerAwards.jpg/330px-SEKAINOOWARISpaceShowerAwards.jpg",
  "RADWIMPS": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Radwinps2016.jpg/330px-Radwinps2016.jpg",
  "Hoshino Gen": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/GenHoshino2017.jpg/330px-GenHoshino2017.jpg",
  "Naniwa Danshi": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Naniwa_Danshi.jpg/330px-Naniwa_Danshi.jpg",
  "Zico & Lilas": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/ZICO_Damiani_May_2024.jpg/330px-ZICO_Damiani_May_2024.jpg",
  "BOYNEXTDOOR": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/2026-01-16_BOYNEXTDOOR_at_Golden_Disc_Awards_05_%28cropped%29.png/330px-2026-01-16_BOYNEXTDOOR_at_Golden_Disc_Awards_05_%28cropped%29.png",
  "aespa": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/241005_aespa_K-Link_Festival_%28cropped%29.jpg/330px-241005_aespa_K-Link_Festival_%28cropped%29.jpg",
  "Hearts2Hearts": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/260221_HEARTS2HEARTS_%40_2026_Fanmeeting_HEARTS2HOUSE.jpg/330px-260221_HEARTS2HEARTS_%40_2026_Fanmeeting_HEARTS2HOUSE.jpg",
  "Sik-K & Lil Moshpit": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Sik-K_2020.png/330px-Sik-K_2020.png",
  "Snow Man": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Snow_Man.jpg/330px-Snow_Man.jpg",
  "LE SSERAFIM": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Le_Sserafim_at_2026_Golden_Disc_awards.png/330px-Le_Sserafim_at_2026_Golden_Disc_awards.png",
  "Playboi Carti": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Playboi_Carti%2C_Clout_Festival_2024_05_%28cropped%29.jpg/330px-Playboi_Carti%2C_Clout_Festival_2024_05_%28cropped%29.jpg"
}

export function artistPhotoFor(name: string): string | undefined {
  return ARTIST_PHOTOS[name]
}
